void deletionBT(struct Node* root, int key)
{
    if(!root)
    return;
    Node *temp, *current, *del;
    queue<Node*>q;
    queue<Node*>q1;
    q.push(root);
    while(!q.empty())
    {
        current=q.front();
        if(current->key==key)
            del=current;
        if(current->left)
            q.push(current->left);
        if(current->right)
            q.push(current->right);
        q.pop();
    }
    temp=current;
    del->key=current->key;
    q1.push(root);
    while(!q1.empty())
    {
        current=q1.front();
        if(current->left)
        {
            if(current->left==temp)
            {
                current->left=NULL;
                return;
            }
            else
                q1.push(current->left);
        }
        if(current->right)
        {
            if(current->right==temp)
            {
                current->right=NULL;
                return;
            }
            else
                q1.push(current->right);
        }
        q1.pop();
    }
    // code here
}
